#!/bin/bash -e
j=$(om -t https://$OPS_MGR_HOST -k -u $OPS_MGR_USR -p $OPSPW curl -s -p "/api/v0/staged/products/")
p=$(jq -r '.[].guid' <<< $j | grep -iw "cf-*")

c=$(om -t https://$OPS_MGR_HOST -k -u $OPS_MGR_USR -p $OPSPW curl -s -p "/api/v0/deployed/products/$p/variables?name=mysql-admin-credentials")
cf=$(jq -r ".[]" <<< $c )

read -a creds <<< $cf

userid=0
u=$(om -t https://$OPS_MGR_HOST -k -u $OPS_MGR_USR -p $OPSPW curl -s -p "/api/v0/deployed/products/$p/variables?name=mysql-admin-credentials" | sed -e s/-//g)
uui=$(jq -r ".mysqladmincredentials.username" <<< $u)
pui=$(jq -r ".mysqladmincredentials.password" <<< $u)

echo $uui
echo $pui
